---
version: "3"
services:
  neo-faucet:
    container_name: neo-faucet
    depends_on:
      - neo-scan
    environment:
      NEOSCAN: "neo-scan:4000"
    image: cityofzion/neo-local-faucet
    links:
      - "neo-scan:4000"
    ports:
      - "4002:4002"

  neo-node1:
    container_name: neo-node1
    image: cityofzion/neo-privatenet:2.7.6
    ports:
      - "20333:20333"
      - "30333:30333"

  neo-python:
    container_name: neo-python
    depends_on:
      - neo-node1
      - neo-scan
    image: cityofzion/neo-python:v0.7.7
    network_mode: host
    tty: true
    volumes:
      - "./smart-contracts:/smart-contracts"
      - "./wallets:/wallets"

  neo-scan:
    container_name: neo-scan
    depends_on:
      - postgres
      - neo-node1
      - notifications-server
    environment:
      HOST: "${HOST_NAME}"
      NEO_NOTIFICATIONS_SERVER: "http://${NOTIFICATIONS_SERVER}:8080/v1"
      NEO_SEED_1: "http://${SEED_SERVER}:30333"
      NEO_SEED_2: "http://${SEED_SERVER}:30334"
      NEO_SEED_3: "http://${SEED_SERVER}:30335"
      NEO_SEED_4: "http://${SEED_SERVER}:30336"
      PORT: 4000
    image: registry.gitlab.com/cityofzion/neo-scan
    links:
      - "neo-node1:30333"
      - "neo-node2:30334"
      - "neo-node3:30335"
      - "neo-node4:30336"
    ports:
      - "4000:4000"

  notifications-server:
    command: "/usr/bin/python3 /neo-python/neo/bin/api_server.py --config /neo-python/custom-config.json --port-rest 8080"
    container_name: notifications-server
    depends_on:
      - neo-node1
    image: cityofzion/neo-python
    ports:
      - "8080:8080"
    volumes:
      - "./notifications-server.config.json:/neo-python/custom-config.json"

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    image: "postgres:10.1"
