---
version: "3"
services:
  neo-faucet:
    container_name: neo-faucet
    depends_on:
      - neo-scan
    environment:
      NEOSCAN: "neo-scan:4000"
    image: cityofzion/neo-local-faucet
    links:
      - "neo-scan:4000"
    ports:
      - "4002:4002"

  neo-privatenet1:
    container_name: neo-privatenet1
    build:
      context: ./privnet
      args:
        NODE_NUMBER: 1
        PORT_NUMBER: 20333
        RPC_PORT_NUMBER: 30333
    ports:
      - "20333:20333"
      - "30333:30333"

  neo-privatenet2:
    container_name: neo-privatenet2
    build:
      context: ./privnet
      args:
        NODE_NUMBER: 2
        PORT_NUMBER: 20334
        RPC_PORT_NUMBER: 30334
    ports:
      - "20334:20334"
      - "30334:30334"
  
  neo-privatenet3:
    container_name: neo-privatenet3
    build:
      context: ./privnet
      args:
        NODE_NUMBER: 3
        PORT_NUMBER: 20335
        RPC_PORT_NUMBER: 30335
    ports:
      - "20335:20335"
      - "30335:30335"
  
  neo-privatenet4:
    container_name: neo-privatenet4
    build:
      context: ./privnet
      args:
        NODE_NUMBER: 4
        PORT_NUMBER: 20336
        RPC_PORT_NUMBER: 30336
    ports:
      - "20336:20336"
      - "30336:30336"

  neo-python:
    container_name: neo-python
    depends_on:
      - neo-privatenet1
      - neo-privatenet2
      - neo-privatenet3
      - neo-privatenet4
      - neo-scan
    image: cityofzion/neo-python:v0.7.7
    network_mode: host
    tty: true
    volumes:
      - "./smart-contracts:/smart-contracts"
      - "./wallets:/wallets"

  neo-scan:
    container_name: neo-scan
    depends_on:
      - postgres
      - neo-privatenet1
      - neo-privatenet2
      - neo-privatenet3
      - neo-privatenet4
      - notifications-server
    environment:
      HOST: "${HOST_NAME}"
      NEO_NOTIFICATIONS_SERVER: "http://${NOTIFICATIONS_SERVER}:8080/v1"
      NEO_SEED_1: "http://neo-privatenet1:30333"
      NEO_SEED_2: "http://neo-privatenet2:30334"
      NEO_SEED_3: "http://neo-privatenet3:30335"
      NEO_SEED_4: "http://neo-privatenet4:30336"
      PORT: 4000
    image: registry.gitlab.com/cityofzion/neo-scan
    links:
      - "neo-privatenet1:30333"
      - "neo-privatenet2:30334"
      - "neo-privatenet3:30335"
      - "neo-privatenet4:30336"
    ports:
      - "4000:4000"

  notifications-server:
    command: "/usr/bin/python3 /neo-python/neo/bin/api_server.py --config /neo-python/custom-config.json --port-rest 8080"
    container_name: notifications-server
    depends_on:
      - neo-privatenet1
      - neo-privatenet2
      - neo-privatenet3
      - neo-privatenet4
    image: cityofzion/neo-python
    ports:
      - "8080:8080"
    volumes:
      - "./notifications-server.config.json:/neo-python/custom-config.json"

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    image: "postgres:10.1"
